stages:
  - build
  - test

build:
  stage: build
  image: golang:1.22-bullseye
  script:
    - go mod tidy
    - make build


before_script:
  - go install github.com/t-yuki/gocover-cobertura@latest

test:
  stage: test
  image: golang:1.22-bullseye
  script:
      - make deps
      - make coverage-cobertura
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
