stages:
  - build
  - test

build:
  stage: build
  image: golang:latest
  script:
    - go mod tidy
    - make build
  only:
    - devtask/GOJHW-3

test:
  stage: test
  image: golang:latest
  script:
      - go mod tidy
      - go install
      - go test ./... -coverprofile=coverage.txt -covermode=count
      - go get github.com/boumenot/gocover-cobertura
      - gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
  only:
    - devtask/GOJHW-3
